boat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # new


urlpatterns = [path("admin/", admin.site.urls), path("", include("core.urls"))]

core/models.py
import os
from django.db import models
from django.urls import reverse


class Operator(models.Model):
    class Meta:
        ordering = ["name"]

    class AssociationChoices(models.TextChoices):
        ATBOWATON = (
            "atbo",
            "Association of Tourists Boat Operators and Water Transporters of Nigeria",
        )
        UFTA = "ufta", "United Ferry Transporters' Association"
        IBOA = "iboa", "Integrated Boat Operators Association"

    name = models.CharField(max_length=255, unique=True)
    contact_info = models.CharField(max_length=255)
    operation_commenced = models.IntegerField()
    association = models.CharField(
        max_length=4,
        choices=AssociationChoices.choices,
        default=AssociationChoices.ATBOWATON,
    )

    def __str__(self):
        return self.name

    def __repr__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse("dashboard_operator_detail", kwargs={"pk": self.pk})

    @property
    def boats(self):
        return Boat.objects.filter(operator=self).count()

    @property
    def reviews(self):
        boats = Boat.objects.filter(operator=self)
        reviews = [Review.objects.filter(boat=boat).count() for boat in boats]
        return sum(reviews)

    @property
    def average_rating(self):
        return 4.5


class Boat(models.Model):
    class Meta:
        unique_together = ["name", "operator"]
        ordering = ["name"]

    def rename_captain_boat_photo_path(instance, filename) -> str:
        basefilename, file_extension = os.path.splitext(filename)
        return f"mediafiles/captains/{instance.operator.name.lower()}_{instance.name.lower()}{file_extension}"

    def rename_deckhand_boat_photo_path(instance, filename) -> str:
        basefilename, file_extension = os.path.splitext(filename)
        return f"mediafiles/deckhands/{instance.operator.name.lower()}_{instance.name.lower()}{file_extension}"

    name = models.CharField(max_length=100)
    capacity = models.IntegerField()
    captain_name = models.CharField(max_length=100)
    captain_certification = models.CharField(max_length=1000, default="")
    captain_photo = models.ImageField(upload_to="mediafiles/captains/")
    deckhand_name = models.CharField(max_length=100)
    deckhand_photo = models.ImageField(upload_to=rename_deckhand_boat_photo_path)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE)
    niwa_approval_date = models.DateField()
    laswa_approval_date = models.DateField()
    certification_status = models.CharField(max_length=1000, default="")

    def __str__(self):
        return self.name

    @property
    def reviews(self):
        return Review.objects.filter(boat=self).order_by("created")

    @property
    def reviews_count(self):
        return self.reviews.count()


class Review(models.Model):
    class Meta:
        ordering = ["-created"]

    content = models.TextField()
    boat = models.ForeignKey(Boat, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.boat.name} {self.created}"

templates/customer/boat_detail.html
{% extends "base.html" %}
{% block content %}
  <main id="main">
    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg">
      <div class="container">
        <div class="section-title boats-heading1">
          <div class="row section-title1 boats-heading3">
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
              <div class="member">
                <div class="member-info">
                  <h4>{{ boat.name }}</h4>
                  <span>
                    <b>LASWA Approval: {{ boat.laswa_approval_date }}</b></span
                  >
                  <span>
                    <b> NIWA Approval: {{ boat.niwa_approval_date }}</b>
                  </span>
                  <span>
                    <b> Certification Status: {{ boat.certification_status }}</b>
                  </span>
                  <span> <b> Rating: {{ boat.reviews_count }}</b> </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row boats-heading2">
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img height=""
                     width=""
                     src="{{ boat.captain_photo.url }}"
                     class="img-fluid"
                     alt="captain"/>
              </div>
              <div class="member-info">
                <h4>Captain</h4>
                <span>{{ boat.captain_name }}</span>
                <span>Certifications: {{ boat.captain_certification }}</span>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img height=""
                     width=""
                     src="{{ boat.deckhand_photo.url }}"
                     class="img-fluid"
                     alt="deckhand"/>
              </div>
              <div class="member-info">
                <h4>Deckhand</h4>
                <span>{{ boat.deckhand_name }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Team Section -->
    <div class="container">
      <div class="container my-5 py-5 text-area">
        <div class="row d-flex justify-content-center text-area">
          <div class="col-md-12 col-lg-10 col-xl-8">
            <form class="card" action="{% url 'one_boat' boat.pk %}" method="post">
              {% csrf_token %}
              <div class="card-footer py-3 border-0">
                <div class="d-flex flex-start w-100">
                  <div class="form-outline w-100">
                    <textarea class="form-control"
                              id="textAreaExample"
                              placeholder="Have a comment?"
                              rows="4"
                              name="content"
                              style="background: #fff"></textarea>
                  </div>
                </div>
                <div class="float-end mt-2 pt-1">
                  <button type="submit" class="btn btn-secondary btn-sm">Post comment</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- </section> -->
      <div class="review-list">
        <ul>
          {% for review in reviews %}
            <li>
              <div class="d-flex d-flex1">
                <div class="right">
                  <div class="review-description">
                    <p>{{ review.content }}</p>
                  </div>
                <span class="publish py-3 d-inline-block w-100">Published {{ review.created }}</span
                >
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</main>
{% endblock content %}

templates/customer/boat_list.html
{% extends "base.html" %}
{% block content %}

    <main id="main">

      <!-- ======= Team Section ======= -->
      <section id="team" class="team section-bg">
        <div class="container" >
          <div class="section-title boats-heading">
            <div class="row section-title1">
                <div
                  class="col-lg-3 col-md-6 d-flex align-items-stretch"
                  
                  
                >
                  <div class="member ">
                    <div class="member-info">
                      <h4>R & N</h4>
                      <span> <b>Contact: +23480983289</b></span>
                      <span> <b> Association: ATBOWATON</b> </span>
                      <span> <b> Total Boats: 10</b> </span>
                    </div>
                  </div>
                </div>
            </div>
          </div>

          <div class="row">
            <div
              class="col-lg-3 col-md-6 d-flex align-items-stretch"
              
              
            >
              <div class="member">
                <div class="member-img">
                  <img
                    src="assets/img/team/user.png"
                    class="img-fluid"
                    alt=""
                  />
                </div>
                <div class="member-info">
                  <h4>R&N 4</h4>
                  <span>Asowaja Dola Ased</span>
                </div>
              </div>
            </div>

            <div
              class="col-lg-3 col-md-6 d-flex align-items-stretch"
              
              
            >
              <div class="member">
                <div class="member-img">
                  <img
                    src="assets/img/team/user.png"
                    class="img-fluid"
                    alt=""
                  />
                </div>
                <div class="member-info">
                  <h4>Walter White</h4>
                  <span>Chief Executive Officer</span>
                </div>
              </div>
            </div>

            <div
              class="col-lg-3 col-md-6 d-flex align-items-stretch"
              
              
            >
              <div class="member">
                <div class="member-img">
                  <img
                    src="assets/img/team/user.png"
                    class="img-fluid"
                    alt=""
                  />
                </div>
                <div class="member-info">
                  <h4>Walter White</h4>
                  <span>Chief Executive Officer</span>
                </div>
              </div>
            </div>

            <div
              class="col-lg-3 col-md-6 d-flex align-items-stretch"
              
              
            >
              <div class="member">
                <div class="member-img">
                  <img
                    src="assets/img/team/user.png"
                    class="img-fluid"
                    alt=""
                  />
                </div>
                <div class="member-info">
                  <h4>Walter White</h4>
                  <span>Chief Executive Officer</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- End Team Section -->
    </main>
{% endblock content %}

templates/customer/business_list.html
{% extends "base-tailwind.html" %}
{% block content %}
    <!-- component -->
    <div class="bg-white p-8 rounded-md w-full">
        <div class=" flex items-center justify-between pb-6">
            <div>
                <h2 class="text-gray-600 font-semibold">Businesses</h2>
                <span class="text-xs">All businesses</span>
            </div>
            <div class="flex items-center justify-between">
                <div class="flex bg-gray-50 items-center p-2 rounded-md">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-5 w-5 text-gray-400"
                         viewBox="0 0 20 20"
                         fill="currentColor">
                        <path fill-rule="evenodd"
                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                        clip-rule="evenodd" />
                    </svg>
                    <input class="bg-gray-50 outline-none ml-1 block "
                           type="text"
                           name="search"
                           id="search"
                           placeholder="search..."/>
                </div>
            </div>
        </div>
        <div>
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full leading-normal">
                        <thead>
                            <tr>
                                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    #
                                </th>
                                <th class="px-5 py-3 border-b-2 text-center border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Business Name
                                </th>
                                <th class="px-5 py-3 border-b-2 text-center border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Owner Contact
                                </th>
                                <th class="px-5 py-3 border-b-2 text-center border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Boats
                                </th>
                                <th class="px-5 py-3 border-b-2 text-center border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Average Rating
                                </th>
                                <th class="px-5 py-3  text-center border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Operation Commenced
                                </th>
                                <th class="px-5 text-center py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for business in businesses %}
                                <tr>
                                    <td td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">{{ forloop.counter }}</td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                        <p class="text-gray-900 whitespace-no-wrap text-center">{{ business.name }}</p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                        <p class="text-gray-900 whitespace-no-wrap text-center">{{ business.owner }}</p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm text-center">{{ business.boats }}</td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                        <p class="text-gray-900 whitespace-no-wrap text-center">
                                            {{ business.reviews }}
                                            {% comment %} <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                        <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                        <span class="relative">Activo</span>
                                            </span> {% endcomment %}
                                        </p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                        <p class="text-gray-900 whitespace-no-wrap text-center">{{ business.operation_commenced }}</p>
                                    </td>
                                    <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                        <div class="flex justify-center">
                                            <a href="{% url 'business_detail' business.pk %}">
                                                <button>
                                                    <svg xmlns="http://www.w3.org/2000/svg"
                                                         class="h-6 w-6 hover:text-blue-600 rounded-full hover:bg-gray-100 p-1"
                                                         viewBox="0 0 20 20"
                                                         fill="currentColor">
                                                        <path
                                                        d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z" />
                                                        <path
                                                        d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z" />
                                                    </svg>
                                                </button>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between">
                        <span class="text-xs xs:text-sm text-gray-900">Showing 1 to 4 of 50 Entries</span>
                        <div class="inline-flex mt-2 xs:mt-0">
                            <button class="text-sm text-indigo-50 transition duration-150 hover:bg-indigo-500 bg-indigo-600 font-semibold py-2 px-4 rounded-l">
                                Prev
                            </button>
                            &nbsp; &nbsp;
                            <button class="text-sm text-indigo-50 transition duration-150 hover:bg-indigo-500 bg-indigo-600 font-semibold py-2 px-4 rounded-r">
                                Next
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/customer/one_boat.html
{% extends "base.html" %}
{% block content %}


<main id="main">
    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg ">
      <div class="container ">
        <div class="section-title boats-heading1">
          <div class="row section-title1 boats-heading3">
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
              <div class="member">
                <div class="member-info">
                  <h4>R&N 4</h4>
                  <span> <b>LASWA Approval: 10th August 2020</b></span>
                  <span> <b> NIWA Approval: 26th August 2020</b> </span>
                  <span> <b> Certification Status: Lorem Ipsum</b> </span>
                  <span> <b> Rating: 3.8</b> </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row boats-heading2">
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img
                  src="assets/img/team/user.png"
                  class="img-fluid"
                  alt=""
                />
              </div>
              <div class="member-info">
                <h4>Captain</h4>
                <span>Asowaja Dola Ased</span>
                <span>Certifications: Lorem Ipsum, Opsim Dorim</span>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <div class="member-img">
                <img
                  src="assets/img/team/user.png"
                  class="img-fluid"
                  alt=""
                />
              </div>
              <div class="member-info">
                <h4>Deckhand</h4>
                <span>Asowaja Dola Ased</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Team Section -->
    <div class="container">
          <div class="container my-5 py-5 text-area">
            <div class="row d-flex justify-content-center text-area">
              <div class="col-md-12 col-lg-10 col-xl-8">
                <div class="card">
                  <div class="card-footer py-3 border-0">
                    <div class="d-flex flex-start w-100">
                      <div class="form-outline w-100">
                        <textarea class="form-control" id="textAreaExample" placeholder="Have a comment?" rows="4"
                          style="background: #fff;"></textarea>
                      </div>
                    </div>
                    <!-- <div class="rating">
    
                      <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                      <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                      <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                      <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                      <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
                    </div> -->
                    
                    <div class="float-end mt-2 pt-1">
                      <button type="button" class="btn btn-secondary btn-sm">
                        Post comment
                      </button>
                      <button type="button" class="btn btn-outline-secondary btn-sm">
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <!-- </section> -->
    
        <div class="review-list">
            <ul>
                <li>
                    <div class="d-flex d-flex1">
                        
                        <div class="right">
                            <h4>
                                Askbootstrap
                                <span class="gig-rating text-body-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" width="15" height="15">
                                        <path
                                            fill="currentColor"
                                            d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"
                                        ></path>
                                    </svg>
                                    5.0
                                </span>
                            </h4>
                            <div class="country d-flex align-items-center">
                                <span>
                                    <img class="country-flag img-fluid" src="https://bootdey.com/img/Content/avatar/avatar6.png" />
                                </span>
                                <div class="country-name font-accent">India</div>
                            </div>
                            <div class="review-description">
                                <p>
                                    The process was smooth, after providing the required info, Pragyesh sent me an outstanding packet of wireframes. Thank you a lot!
                                </p>
                            </div>
                            <span class="publish py-3 d-inline-block w-100">Published 4 weeks ago</span>
                            
                        </div>
                        <div class="right">
                          <h4>
                              Askbootstrap
                              <span class="gig-rating text-body-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" width="15" height="15">
                                      <path
                                          fill="currentColor"
                                          d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"
                                      ></path>
                                  </svg>
                                  5.0
                              </span>
                          </h4>
                          <div class="country d-flex align-items-center">
                              <span>
                                  <img class="country-flag img-fluid" src="https://bootdey.com/img/Content/avatar/avatar6.png" />
                              </span>
                              <div class="country-name font-accent">India</div>
                          </div>
                          <div class="review-description">
                              <p>
                                  The process was smooth, after providing the required info, Pragyesh sent me an outstanding packet of wireframes. Thank you a lot!
                              </p>
                          </div>
                          <span class="publish py-3 d-inline-block w-100">Published 4 weeks ago</span>
                          
                      </div>
                      <div class="right">
                        <h4>
                            Askbootstrap
                            <span class="gig-rating text-body-2">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" width="15" height="15">
                                    <path
                                        fill="currentColor"
                                        d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"
                                    ></path>
                                </svg>
                                5.0
                            </span>
                        </h4>
                        <div class="country d-flex align-items-center">
                            <span>
                                <img class="country-flag img-fluid" src="https://bootdey.com/img/Content/avatar/avatar6.png" />
                            </span>
                            <div class="country-name font-accent">India</div>
                        </div>
                        <div class="review-description">
                            <p>
                                The process was smooth, after providing the required info, Pragyesh sent me an outstanding packet of wireframes. Thank you a lot!
                            </p>
                        </div>
                        <span class="publish py-3 d-inline-block w-100">Published 4 weeks ago</span>
                        
                    </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
  
  </main>

{% endblock content %}

templates/customer/operator_detail.html
{% extends "base.html" %}
{% block content %}
    <main id="main">
        <!-- ======= Team Section ======= -->
        <section id="team" class="team section-bg">
            <div class="container">
                <div class="section-title boats-heading">
                    <div class="row section-title1 d-flex align-items-center">
                        <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                            <div class="member ">
                                <div class="member-info">
                                    <h4>{{ operator.name }}</h4>
                                    <span> <b>Contact: {{ operator.contact_info }}</b></span>
                                    <span> <b> Association: {{ operator.get_association_display }}</b> </span>
                                    <span> <b> Total Boats: {{ operator.boats }}</b> </span>
                                </div>
                            </div>
                        </div>
                        <div class=" col-md-6 col-lg-3">
                            <div class="form-outline">
                                <input type="search"
                                       id="JsSearchQuery"
                                       class="form-control"
                                       placeholder="Search here"/>
                                <!-- </div> -->
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4" id="jsBoatContainer">
                        {% for boat in boats %}
                            <a href="{% url 'one_boat' boat.pk %}"
                               class="col-lg-3 col-md-6 d-flex align-items-stretch">
                                <div class="member">
                                    <div class="member-img">
                                        <img height=""
                                             width=""
                                             src="{{ boat.captain_photo.url }}"
                                             class="img-fluid"
                                             alt="captain"/>
                                    </div>
                                    <div class="member-info">
                                        <h4>{{ boat.name }}</h4>
                                        <span>{{ boat.captain_name }}</span>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </section>
            <!-- End Team Section -->
        </main>
    {% endblock content %}
    {% block scripts %}
        {% include "search_scripts_cards.html" %}
    {% endblock scripts %}